name: CI

on: [push, pull_request]

jobs:

  build:
    runs-on: gcc
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: System Setup
      run: |
        apt-get update
        apt-get install meson ninja-build

    - name: Meson Build
      run: |
        meson build

    - name: Compile
      run: |
        ninja -C build

    - name: Run Tests
      run: |
        ninja test -C build
