name: CI

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: System Setup
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build
        sudo pip3 install setuptools
        sudo pip3 install meson

    - name: Meson Build
      run: |
        meson build

    - name: Compile
      run: |
        ninja -C build -Dcpp_std=c++11

    - name: Run Tests
      run: |
        ninja test -C build
